create or replace task ADAPT_TESTING.ADAPT_SCHEMA.Pipeline_Snowflake_Job
	warehouse=COMPUTE_WH
	schedule='1 MINUTE'
	as insert into  ADAPT_TESTING.ADAPT_SCHEMA.HIGH_SAL
(EMP_ID,EMP_JOB,EMP_NAME,EMP_LOCATION,JOINING_DATE,emp_dep,EMP_SAL,EMP_ANOTHER_ADDRESS,EMERGENCY_CONTACT_PERSON,OFFICE_EMAIL,EMP_IS_ACTIVE,EMP_DOB,
EMP_CONTACT_NUMBER) 
(select a.EMP_ID,a.EMP_JOB,a.EMP_NAME,a.EMP_LOCATION,a.JOINING_DATE,b.emp_dep,b.EMP_SAL,a.EMP_ANOTHER_ADDRESS,a.EMERGENCY_CONTACT_PERSON,a.OFFICE_EMAIL,a.EMP_IS_ACTIVE,a.EMP_DOB,a.EMP_CONTACT_NUMBER from ADAPT_SCHEMA.EMPLOYEE a join ADAPT_SCHEMA.salary b on a.EMP_ID=b.EMP_ID
where b.EMP_SAL>5000)