default:
  outputs:
    dev:
      account: aggnvrr-lb09480
      database: ADAPT_TESTING
      password: MyPass1234@
      role: accountadmin
      schema: ADAPT_SCHEMA
      threads: 4
      type: snowflake
      user: adubey1
      warehouse: COMPUTE_WH
  target: dev
